server:
  port: 8082

spring:
  config:
    import: "classpath:application-core.yml"

  application:
    name: member-service

  kafka:
    bootstrap-servers: 13.125.251.87:9092   # 카프카 주소
    consumer:
      group-id: test-group                # 컨슈머 그룹
      auto-offset-reset: earliest       # 처음부터 읽기
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:mysql://3.35.52.90:3306/member?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: member_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j
#      tracing:
#        include-parameter-values: true

  jpa:
    hibernate:
      ddl-auto: none # ???? ?????? ???? ???? (none, update, create, create-drop)
    properties:
      hibernate:
#        show-sql: true # SQL ?? ??
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.springframework:
      security: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka




