spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: admin_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
