spring:
  jpa:
    hibernate:
      ddl-auto: none # ???? ?????? ???? ???? (none, update, create, create-drop)
    properties:
      hibernate:
#        show-sql: true # SQL ?? ??
        format_sql: true
        default_batch_fetch_size: 100
